# Generated by Django 6.0.1 on 2026-06-21 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_histories', to='requests.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nss_verified_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_histories', to='donors.donorprofile'),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_registrations', to='donors.donorprofile'),
        ),
        migrations.AddConstraint(
            model_name='donationhistory',
            constraint=models.UniqueConstraint(fields=('donor', 'request'), name='unique_donation_history_per_request'),
        ),
        migrations.AddConstraint(
            model_name='campregistration',
            constraint=models.UniqueConstraint(fields=('donor', 'camp'), name='unique_camp_registration_per_donor'),
        ),
    ]
