# Generated by Django 5.0.6 on 2026-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='last_cooldown_alert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
