# Generated by Django 5.0.6 on 2026-07-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('BLOOD_REQUEST', 'New Blood Request'), ('DONATION_COMPLETE', 'Completed Donation'), ('DONOR_REGISTER', 'New Donor Registration'), ('DONOR_VERIFICATION', 'Donor Verification'), ('HOSPITAL_ACTION', 'Hospital Action'), ('BLOOD_BANK_ACTION', 'Blood Bank Action'), ('CAMP_ACTION', 'Blood Camp Activity'), ('BROADCAST_ACTION', 'Mass Message'), ('ADMIN_LOGIN', 'Admin Login'), ('REQUEST_DECISION', 'Request Approval/Rejection')], db_index=True, max_length=50),
        ),
    ]
