# Generated by Django 5.0.6 on 2026-08-19 15:22

import django.db.models.deletion
import donors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcamp',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='camps/covers/', validators=[donors.models.validate_camp_image]),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='district',
            field=models.CharField(db_index=True, default='Purnia', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='manual_donation_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='organizer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='organizer_name',
            field=models.CharField(default='NSS Coordinator', max_length=120),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='status',
            field=models.CharField(choices=[('AUTO', 'Automatic (Based on Date/Time)'), ('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], db_index=True, default='AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.bloodcamp'),
        ),
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camps/gallery/', validators=[donors.models.validate_camp_image])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='donors.bloodcamp')),
            ],
            options={
                'db_table': 'blooddonation_campimage',
            },
        ),
    ]
