# Generated by Django 5.0.6 on 2026-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_bloodcamp_cover_image_bloodcamp_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='donors/profiles/'),
        ),
    ]
