# Generated by Django 6.0.1 on 2026-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0008_alter_bloodrequest_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcamp',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
