# Generated by Django 5.0.6 on 2026-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_bloodrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
