# Generated by Django 5.0.6 on 2026-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'blooddonation_bloodbank',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_bank',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
