# Generated by Django 5.0.6 on 2026-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_bloodbank_bloodrequest_blood_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Donor Assigned'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
