# Generated by Django 5.0.6 on 2026-08-22 04:08

from django.db import migrations

def create_dummy_facilities(apps, schema_editor):
    Hospital = apps.get_model('requests', 'Hospital')
    BloodBank = apps.get_model('requests', 'BloodBank')
    
    districts = [
        "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar",
        "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar",
        "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur",
        "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran",
        "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"
    ]
    
    hospital_data = []
    bloodbank_data = []
    
    for district in districts:
        hospital_data.extend([
            Hospital(name=f"{district} Sadar Hospital", city=district, address=f"Main Road, {district}", is_active=True),
            Hospital(name=f"City Care Hospital {district}", city=district, address=f"Station Road, {district}", is_active=True)
        ])
        
        bloodbank_data.extend([
            BloodBank(name=f"{district} Red Cross Blood Bank", city=district, address=f"Red Cross Society, {district}", is_active=True),
            BloodBank(name=f"Sanjeevani Blood Centre {district}", city=district, address=f"Civil Lines, {district}", is_active=True)
        ])
        
    Hospital.objects.bulk_create(hospital_data, ignore_conflicts=True)
    BloodBank.objects.bulk_create(bloodbank_data, ignore_conflicts=True)

def remove_dummy_facilities(apps, schema_editor):
    # Do nothing on unapply, to preserve manually added ones
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_bloodrequest_prescription_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.RunPython(create_dummy_facilities, remove_dummy_facilities),
    ]
